package com.wikitude.wikitudestudioandroidapptemplate;

public class WikitudeSDKConstants {
	

	/**
	 * enter valid license key here to get rid of watermarkin. Note: Ensure to choose a new and unique package name up front (e.g. com.yourcompany.yourappname)
	 */
	protected static final String WIKITUDE_SDK_KEY = "NEnLPofrFs/9GMiiiQyitAFAErfxhQq/0kowZhEfC3UvJBhTFCEQWHsDLYH74Z/GnjvUZtK1IgkNmcs5HNii4xyQFWpCQM07Pb7d2oJsba0MKxvwnpetzvmZmQMxmajVfVQwZVhzoII6D9Yqy0+mQiBLz9Vjg/mM8UuU4do8iiBTYWx0ZWRfX8uU/XsLLIUoeDaxAeadJG7M5GijfNh5cvOJXqNlINJDTPlYrwBNOGkHvSvpRXw4Uw02uucM4DHwKMvbwZY9Qelxe1vQPsrgvIehABB5W0jO8OSKay7rs+KfcFTu3cfhg/1pO/02zCvJJ8KUd1aSbFDk1GS85dC1ytPcs9dMP+X7ohD0MarjWNtOnWTp8wc0GPBmyg1zFeObLpnQrC8CeIVOrobT3GoMsJNZllX5CMr+9O9KKfOBevSYElEfLBFDfBe2PIplTWR97Z6LFPMIf+vgEJnzKHQM0TyPt3ZKOhpqMdcL+5SwH4TdWQmld9JNedwHF1B5vLhhFeX/IBRJsTd3BqBp8LTWPKGjeQjDofm6vq/1xGGCtMVqjC14X664a3gblEMSR+brLXcym/rYA20OV0y9mOX0esl5aaoKppVwStXQMMdoRYcAk4m0V9G4wOSWHQ17INIVosZUdfQttzDEEP/ScRfoaM9dguGwUGYStpRWEVrLWyeTob0Djwsi8dP5ml/SEMfQWw3UOc9D/OgMdN+9MQvLxBvMFXjp+QZFhUXUhUHtIgDIMpnjNSwmXbLHk0I4C7z4589KeI5SU92vCqxy5HDgAVC7jtD7AMzs5dCvoYUs8D/1XfoVcKtKdr4DHLI/S42UvSMUq8nCt+mxbGDIqByRRpYG4HtUJtRQcEuO2l1FcHaPIGbuE+efjx9eQhNBTOAJ";

}
